[theme]
base="light"
primaryColor="#10B981"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F3F4F6"
textColor="#111111"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
